stages:
  download:
    cmd: .venv/bin/python scripts/download.py
    deps:
      - scripts/download.py
    outs:
      - download/EPH_F.xpt
      - download/EPH_G.xpt
      - download/EPHPP_H.xpt
      - download/EPHPP_I.xpt
      - download/DEMO_F.xpt
      - download/DEMO_G.xpt
      - download/DEMO_H.xpt
      - download/DEMO_I.xpt
  process:
    cmd: .venv/bin/python scripts/process.py
    deps:
      - scripts/process.py
      - download/EPH_F.xpt
      - download/EPH_G.xpt
      - download/EPHPP_H.xpt
      - download/EPHPP_I.xpt
      - download/DEMO_F.xpt
      - download/DEMO_G.xpt
      - download/DEMO_H.xpt
      - download/DEMO_I.xpt
    outs:
      - brick/environmental_phenols.parquet
      - brick/demographics.parquet
      - brick/phenols_with_demographics.parquet
