stages:
  download:
    cmd: .venv/bin/python scripts/download.py
    deps:
      - scripts/download.py
    outs:
      - download/:
          persist: true
  process:
    cmd: .venv/bin/python scripts/process.py
    deps:
      - scripts/process.py
      - download/
    outs:
      - brick/:
          persist: true
